org: aatishdubey123
app: http-crud-items-test
service: http-crud-items-test
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  environment:
    DB_TABLE: ${self:service}-${sls:stage}
    PRIMARY_KEY: id
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:provider.environment.DB_TABLE}"
  httpApi:
    cors:
      allowedOrigins:
      - 'https://cozy-praline-e3dec4.netlify.app'
      - 'http://127.0.0.1:5173'
    authorizers:
      CognitoAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_7qMKR8qY5
        audience:
        - 10cj58s3hamc8v79ls4kkitv0v

functions:
  createItem:
    memorySize: 256
    handler: createItem.handler
    events:
      - httpApi:
          path: /
          method: post
          authorizer: 
            name: CognitoAuthorizer
  deleteItem:
    memorySize: 256
    handler: deleteItem.handler
    events:
      - httpApi:
          path: /{id}
          method: delete
          authorizer: 
            name: CognitoAuthorizer
  getItems:
    memorySize: 256
    handler: getItems.handler
    events:
      - httpApi:
          path: /
          method: get
          authorizer: 
            name: CognitoAuthorizer
resources:
  Resources:
    ItemsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        TableName: ${self:service}-${sls:stage}
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1